version: "4"

services:

  frontend:
      image: nginx
      container_name: LLMfrontend
      build:
        context: ./nginx
      ports:
        - "80:80"
      restart: always
      
      depends_on:
        - backend
      

  backend:
    image: backend
    container_name: LLMbackend
    build:
      context: ./backend
    environment:
        - SECRET_KEY=${SECRET_KEY}
        - ALLOWED_HOSTS=${ALLOWED_HOSTS}
        - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
        - DEBUG=1
    restart: always
